/* Generated by AntZ Content Studio. */
window.ANTZ_REVIEW_DATA = {
  "initialCount": 4,
  "googleReviewsUrl": "https://maps.app.goo.gl/pMG2JZh64t93f5Rj6?g_st=ac",
  "apgl": [
    {
      "name": "Ana",
      "stars": 5,
      "text": "Antoine is a very engaging guitar teacher. My son has really enjoyed his first month of guitar lesson. We will continue to book many more.",
      "year": 2026,
      "avatarImage": "assets/image-2152b30957f6.webp"
    },
    {
      "name": "Iris Dos Santos",
      "stars": 5,
      "text": "Antoine is a fantastic guitar teacher! He’s fun, enthusiastic, and quickly picks up on my daughter’s strengths so he can build on them. He gives great tips to help her progress and even offers helpful recommendations on equipment to support her learning. He’s also very flexible and willing to work around our schedule. We’re very happy with her progress and highly recommend him!",
      "year": 2026,
      "initial": "I",
      "avatarColor": "#8e24aa"
    },
    {
      "name": "Edward Naish",
      "stars": 5,
      "text": "Our daughter loves Antoine's piano lessons. He makes them fun and accessible which helps no end in her progress and enthusiasm.",
      "year": 2026,
      "initial": "E",
      "avatarColor": "#e64a19"
    },
    {
      "name": "Joe Tamura",
      "stars": 5,
      "text": "Antoine is very nice and friendly. You can feel his passion about music and my son enjoyed his first lesson.",
      "year": 2025,
      "initial": "J",
      "avatarColor": "#0b78b7"
    },
    {
      "name": "Sasha",
      "stars": 5,
      "text": "Antoine has been teaching my little boy age 5 for a couple of months now. My son enjoys his piano lessons and looks forward to his regular sessions all the time. Antoine is very patient and always come up with techniques to engage with my son. Highly recommend this amazing teacher!",
      "year": 2022,
      "avatarImage": "assets/image-80face7f4385.webp"
    },
    {
      "name": "rojan jalilvand",
      "stars": 5,
      "text": "Anthony teaches to my little brother, he's very patient and motivating.He makes learning fun and easy, and we’ve seen so much improvement. Highly recommend!",
      "year": 2026,
      "initial": "r",
      "avatarColor": "#0d7fc0"
    },
    {
      "name": "Olga Rakhmanina",
      "stars": 5,
      "text": "My son and daughter just had their first lessons with Antoine. They absolutely loved their lessons and described them as ‘brilliant’. Antoine made both sessions really engaging, he was encouraging them and putting them at ease. They look forward to their next lessons :)",
      "year": 2025,
      "avatarImage": "assets/image-df281173d941.webp"
    },
    {
      "name": "rahul maha",
      "stars": 5,
      "text": "Antoine has just started teaching electric guitar to my 16 year old son who is thoroughly enjoying it. He brings deep knowledge and real life experience to the lessons making them lively and entertaining. Antoine is undoubtedly a great teacher and I recommend him wholeheartedly.",
      "year": 2024,
      "initial": "r",
      "avatarColor": "#65a430"
    },
    {
      "name": "Anita Walk",
      "stars": 5,
      "text": "My daughter had a trial guitar lesson with Antoine today. He was very punctual, polite and professio…",
      "year": 2024,
      "avatarImage": "assets/image-72619561d355.webp"
    },
    {
      "name": "Lisa Cartwright",
      "stars": 5,
      "text": "Antoine has been giving piano lessons to my 7 year old and she’s really enjoying them. He makes it very engaging and easy to understand and fun. His kind and encouraging teaching style helps her enormously. I highly recommend him. Thanks Antoine.",
      "year": 2023,
      "avatarImage": "assets/image-378cfc9be9de.webp"
    },
    {
      "name": "Joe Manjaly",
      "stars": 5,
      "text": "Antoine has a warm, friendly and fun way with kids. Our 4 year old son had his first piano lesson this week and is looking forward to learning more. We have also been grateful for clear prompt and easy communication, as well as flexibility over location.",
      "year": 2024,
      "avatarImage": "assets/image-fe8d119c0d9f.webp"
    },
    {
      "name": "Andrew Morris",
      "stars": 5,
      "text": "Antoine has just started teaching my 7 year old piano. He has a lovely easy manner with her and makes the lessons enjoyable with games and ensuring she is learning the things she wants to learn. I'd recommend lessons with Antoine to anyone.",
      "year": 2023,
      "initial": "A",
      "avatarColor": "#1099a6"
    },
    {
      "name": "Carmelina Kulasingam",
      "stars": 5,
      "text": "My son had his first guitar lesson with Antoine, and thoroughly enjoyed it. Booking regular weekly sessions for the foreseeable! Thanks Antoine for being so accommodating with time changes too.",
      "year": 2024,
      "avatarImage": "assets/image-21c43feb4a09.webp"
    },
    {
      "name": "Dipika Aggarwal",
      "stars": 5,
      "text": "Antoine gave my son a great first lesson on electric guitar. He is friendly and personable, an excellent musician and a patient teacher who explains things well.",
      "year": 2024,
      "initial": "D",
      "avatarColor": "#72a635"
    },
    {
      "name": "Muriel Walckiers et Julian Morgan",
      "stars": 5,
      "text": "We just started piano lessons with Antoine for our 7 years old daughter. Antoine has a lovely, kind and encouraging way to engage her. She really enjoys her lessons and is making progress quickly! Thank you Antoine!",
      "year": 2023,
      "initial": "M",
      "avatarColor": "#2f7d32"
    },
    {
      "name": "Johan Lindstrom",
      "stars": 5,
      "text": "My 11 year old son is really enjoying his guitar lessons with Antoine. Antoine is positive and encouraging and makes the lessons fun!",
      "year": 2023,
      "avatarImage": "assets/image-2a2a5beebcfd.webp"
    },
    {
      "name": "Andrea Hall",
      "stars": 5,
      "text": "Our children really enjoy being taught the guitar by Antoine. His genuine enjoyment of playing instruments comes through and helps with engaging the children in their learning. Next stop - learning the piano too!",
      "year": 2022,
      "initial": "A",
      "avatarColor": "#0797cf"
    },
    {
      "name": "Sandrine N",
      "stars": 5,
      "text": "Antoine has been teaching both my children for the last 3 years and we’ve all been very happy with the lessons. They’ve had face to face and online lessons. Antoine has introduced a fun way to learn and both my children have been making progress while having fun. Thank you Antoine!",
      "year": 2021,
      "avatarImage": "assets/image-a2e8b1053e5f.webp"
    },
    {
      "name": "Jaishree Jaisinghani Vyavaharkar",
      "stars": 5,
      "text": "Antoine has been teaching my children (from ages of 7 and 10) for over 1 year, both in person and on zoom. Antoine has an encouraging and positive manner, motivates them to practice and learn in a supportive environment and makes the lessons fun and engaging. Highly recommend.",
      "year": 2021,
      "initial": "J",
      "avatarColor": "#7896a4"
    },
    {
      "name": "Elif Erkoc",
      "stars": 5,
      "text": "We had our first lesson with Antoine. He seems very knowledgeable and good with kids. My daughter said she had a fun first lesson. We're looking forward to next ones.",
      "year": 2025,
      "initial": "E",
      "avatarColor": "#596fc0"
    },
    {
      "name": "Tiziana Rossetto",
      "stars": 5,
      "text": "My sons have just started piano lessons with Antoine and really like him, how he explains pieces to them and encourages them. He is punctual, professional and friendly. I highly recommend him!",
      "year": 2022,
      "initial": "T",
      "avatarColor": "#9b7a6a"
    },
    {
      "name": "Gergana Hristova",
      "stars": 5,
      "text": "Antoan was great with my 5yo daughter. He is very professional and for sure he knows how to engage her and make teaching looking easy .I believe his method is the most effective for reaching excellent results",
      "year": 2024,
      "initial": "G",
      "avatarColor": "#138f81"
    },
    {
      "name": "Kerry Pearson",
      "stars": 5,
      "text": "Highly recommend Antoine. He was enthusiastic, motivating and kept the keyboard lesson fun for my 10 year old. Zack have him 5 stars!",
      "year": 2023,
      "initial": "K",
      "avatarColor": "#d01668"
    },
    {
      "name": "Karl Bolton",
      "stars": 5,
      "text": "Harry is taking lessons and really enjoying the teaching approach",
      "year": 2025,
      "avatarImage": "assets/image-81af4350471c.webp"
    },
    {
      "name": "Carmelina Filippino",
      "stars": 5,
      "text": "Excellent teacher. I have learnt so much from piano and guitar lessons!",
      "year": 2024,
      "avatarImage": "assets/image-f2180295ce4b.webp"
    }
  ]
};
