/* AntZ V6.6 final fixes; no change to published data. */
(()=>{
'use strict';
if(document.documentElement.dataset.antzV66==='yes')return;
document.documentElement.dataset.antzV66='yes';
const style=document.createElement('style');style.setAttribute('data-antz-finish','v6.6');style.textContent="\n@media(max-width:760px){\n .hero .hero-brandmark{display:none!important}\n .hero-copy .antz-mobile-title-row{display:flex!important;flex-direction:row!important;align-items:center!important;justify-content:space-between!important;gap:13px!important;margin:11px 0 15px!important;min-width:0!important}\n .hero-copy .antz-mobile-title-row h1{flex:1 1 auto!important;min-width:0!important;width:auto!important;max-width:none!important;margin:0!important;line-height:.95!important}\n .hero-copy .antz-mobile-title-row img{display:block!important;flex:0 0 auto!important;width:52px!important;height:52px!important;max-width:16vw!important;max-height:16vw!important;object-fit:contain!important;background:#080808;border-radius:50%!important;border:1px solid #444;box-shadow:0 3px 12px rgba(0,0,0,.4)}\n .reviewpanel .reviewfoot{display:flex!important;gap:12px!important;flex-wrap:wrap!important;align-items:center!important;justify-content:space-between!important;min-height:32px;margin-top:19px!important;margin-bottom:5px!important;line-height:1.45!important}\n .reviewpanel .review-actions{display:block!important;clear:both!important;margin-top:22px!important;padding-top:4px!important}\n .reviewpanel #toggleReviews{display:inline-flex!important;min-height:48px!important;align-items:center!important;justify-content:center!important}\n #originals .afgm-brand-branches{max-width:100%!important}\n}\n@media(max-width:359px){.hero-copy .antz-mobile-title-row img{width:44px!important;height:44px!important}.reviewpanel .reviewfoot{flex-direction:column!important;align-items:flex-start!important;gap:4px!important}}\n.reviewpanel .review-actions{margin-top:22px!important}\n.reviewpanel .reviewfoot{margin-bottom:9px!important}\n@media(min-width:761px){\n .hero{background-position:center,clamp(72px,9vw,220px) center!important}\n .hero-copy .antz-mobile-title-row{display:contents!important}\n .hero-copy .antz-mobile-title-row img{display:none!important}\n}\n@media(min-width:761px) and (max-width:1050px){.hero{background-position:center,6vw center!important}}\n@media(min-width:1500px){.hero{background-position:center,clamp(130px,10vw,230px) center!important}}\n.contactbox .antz-whatsapp-cta{display:inline-flex!important;align-items:center!important;justify-content:center!important;gap:10px!important;background:#25d366!important;border:1px solid #168d40!important;color:#082c16!important;white-space:nowrap;font-weight:850!important;min-height:46px!important}\n.contactbox .antz-whatsapp-cta img{display:block;width:22px;height:22px;object-fit:contain}\n@media(max-width:410px){.contactbox .antz-whatsapp-cta{white-space:normal;padding:11px 15px!important}}\n";document.head.append(style);
const originals=document.getElementById('originals');if(originals){const heading=originals.nextElementSibling;if(heading?.tagName==='H3'&&heading.textContent.trim()==='Competition work'){const p=heading.nextElementSibling;if(p?.tagName==='P'&&p.textContent.includes('Earlier competition entries can be added'))p.remove();heading.remove();}}
const title=document.querySelector('.hero-copy h1'),logo=document.querySelector('.hero-brandmark img');if(title&&logo&&!title.closest('.antz-mobile-title-row')){const row=document.createElement('div');row.className='antz-mobile-title-row';const img=document.createElement('img');img.className='antz-mobile-title-logo';img.src=logo.src;img.alt='AntZ logo';img.width=52;img.height=52;title.parentNode.insertBefore(row,title);row.append(title,img);}
const actions=document.querySelector('.contactbox .actions');if(actions&&!actions.querySelector('.antz-whatsapp-cta')){const a=document.createElement('a');a.href='https://wa.me/447901993421';a.target='_blank';a.rel='noopener noreferrer';a.className='btn antz-whatsapp-cta';a.setAttribute('aria-label','Enquire with AntZ on WhatsApp');const icon=document.querySelector('.hero a.whatsapp img');if(icon){const img=document.createElement('img');img.src=icon.src;img.alt='';img.setAttribute('aria-hidden','true');a.append(img);}const label=document.createElement('span');label.textContent='WhatsApp AntZ';a.append(label);const back=Array.from(actions.querySelectorAll('a')).find(x=>x.getAttribute('href')==='#top');if(back)actions.insertBefore(a,back);else actions.append(a);}
})();
